[package]
name = "timada-starter-client"
version = "0.0.11"
publish = true
edition = "2021"
license = "AGPL-3.0"
description = "A client for timada starter"
repository = "https://github.com/timayz/starter"
homepage = "https://timada.co"
documentation = "https://docs.rs/timada-starter-client"

[dependencies]
tonic = { version = "0.9", features = ["tls"] }
prost = "0.11"
prost-types = "0.11"
prost-derive = "0.11"
http = { version = "0.2", optional = true }
cfg-if = "1.0"

[build-dependencies]
tonic-build = { version = "0.9", features = ["prost"] }

[features]
default = ["client"]
client = ["dep:http"]
