[package]
name = "timada-starter-client"
version = "0.2.4"
publish = true
edition = "2021"
license = "AGPL-3.0"
description = "A client for timada starter"
repository = "https://github.com/timayz/starter"
homepage = "https://timada.co"
documentation = "https://docs.rs/timada-starter-client"

[dependencies]
starter-feed = { path = "../feed", features = ["proto"], version = "0.2.4", optional = true }
tonic = { version = "0.10.0", features = ["tls"] }
prost = "0.12.0"
prost-types = "0.12.0"
prost-derive = "0.12.0"
http = "0.2.9"

[features]
default = []
all = ["feed"]
feed = ["dep:starter-feed"]
