[workspace]

resolver = "2"

members = [
    "./feed",
    "./cli",
    "./client",
    "./api",
    "./core",
    "./components",
    "./app"
]

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true
