[workspace]

resolver = "2"

members = [
    "./starter",
    "./starter-cli",
    "./starter-client",
    "./starter-app"
]

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true

