version: '3.9'

services:
  starter-yugabyte-init:
    image: yugabytedb/yugabyte:2.20.1.0-b97
    command: >
      bin/ysqlsh --host yugabyte --command "
        CREATE DATABASE starter;
        CREATE USER starter; GRANT ALL ON DATABASE starter TO starter WITH GRANT OPTION;
        ALTER USER starter CREATEDB;
        ALTER DATABASE starter OWNER TO starter;
      "
    restart: on-failure
    networks:
      - intranet

networks:
  intranet:
    name: timada
    external: true
