[package]
name = "starter-feed"
version = "0.2.4"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
tonic = { version = "0.10.0", features = ["tls"]}
prost = "0.12.0"
prost-types = "0.12.0"
prost-derive = "0.12.0"

[build-dependencies]
tonic-build = { version = "0.10.0", features = ["prost"] }

[features]
proto = []
