[package]
name = "timada-starter-feed"
version = "0.3.1"
edition = "2021"
license = "AGPL-3.0"
publish = true
description = "Feed module for timada starter"
repository = "https://github.com/timayz/starter"
homepage = "https://timada.co"
documentation = "https://docs.rs/timada-starter-feed"

[dependencies]
tonic = { version = "0.10.0", features = ["tls"] }
prost = "0.12.0"
prost-types = "0.12.0"
prost-derive = "0.12.0"
evento = "0.6.3"
anyhow = "1.0.75"
ulid = "1.1.0"
parse-display = "0.8.2"
serde = "1.0.188"
validator = { version = "0.16.1", features = ["derive"] }
tracing = "0.1.37"

[build-dependencies]
tonic-build = { version = "0.10.0", features = ["prost"] }

[features]
proto = []
