[package]
name = "starter-core"
version = "0.2.4"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
starter-components = { path = "../components", version = "0.2.4" }
leptos = "0.5.0-beta2"
axum = "0.6.20"
serde = "1.0.188"
