[package]
name = "starter-app"
version = "0.2.4"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
#starter-feed = { path = "../feed", version = "0.2.4" }
axum = "0.6.20"
anyhow = "1.0.75"
leptos = "0.5.0-beta2"
tokio = "1.32.0"
tower = { version = "0.4.13", features = ["util"] }
tracing = "0.1.37"
serde = "1.0.188"
config = "0.13.3"
rust-embed = "8.0.0"
mime_guess = "2.0.4"
i18n-embed = { version = "0.13.9", features = ["fluent-system"]}
i18n-embed-fl = "0.6.7"
once_cell = "1.18.0"
unic-langid = "0.9.1"
