[package]
name = "starter-app"
version = "0.2.4"
edition = "2021"
license = "AGPL-3.0"

[package.metadata.cargo-all-features]
denylist = ["axum", "tokio", "tower", "tower-http", "leptos_axum"]
skip_feature_sets = [["ssr", "hydrate"]]

[package.metadata.leptos]
output-name = "starter"
site-root = "target/site"
site-pkg-dir = "starter-pkg"
style-file = "style/main.css"
assets-dir = "public"
site-addr = "127.0.0.1:3000"
reload-port = 3001
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
browserquery = "defaults"
watch = false
env = "DEV"
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
starter-feed = { path = "../feed", version = "0.2.4" }
timada-starter-client = { path = "../client", default-features = false, optional = true, version = "0.2.4" }
axum = { version = "0.6.20", optional = true }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
cfg-if = "1.0.0"
leptos = { version = "0.4.9" }
leptos_axum = { version = "0.4.9", optional = true }
leptos_meta = { version = "0.4.9" }
leptos_router = { version = "0.4.9" }
log = "0.4.20"
simple_logger = "4.2.0"
tonic = { version = "0.9.2", features = ["tls"], optional = true }
prost = { version = "0.11.9", optional = true }
tokio = { version = "1.32.0", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4.3", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.87"
thiserror = "1.0.47"
tracing = { version = "0.1.37", optional = true }
serde = { version = "1.0.185", optional = true }
config = { version = "0.13.3", optional = true }
http = "0.2.9"

[features]
hydrate = [
	"starter-feed/hydrate",
	"leptos/hydrate",
	"leptos_meta/hydrate",
	"leptos_router/hydrate",
]
ssr = [
	"starter-feed/ssr",
	"dep:timada-starter-client",
	"dep:tonic",
	"dep:prost",
	"dep:axum",
	"dep:tokio",
	"dep:tower",
	"dep:tower-http",
	"dep:leptos_axum",
	"leptos/ssr",
	"leptos_meta/ssr",
	"leptos_router/ssr",
	"dep:tracing",
	"dep:config",
	"dep:serde",
]
