[package]
name = "starter"
version = "0.1.0"
edition = "2021"
publish = false
license = "AGPL-3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
