name: CI
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore: 
      - "**/Cargo.toml"
      - "Cargo.lock"
    tags:
      - '*'

jobs:
  test:
    uses: timayz/.github/.github/workflows/service-testing.yml@v2.19.0
    with:
      db_name: starter
    if: "!startsWith(github.ref, 'refs/tags/v')"

  docker:
    uses: timayz/.github/.github/workflows/docker.yml@v2.19.0
    with:
      image: timayz/starter
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  cargo:
    uses: timayz/.github/.github/workflows/cargo-publish.yml@v2.19.0
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release:
    needs: [test, docker, cargo]
    uses: timayz/.github/.github/workflows/service-release.yml@v2.19.0
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') && !startsWith(github.ref, 'refs/tags/v')
