name: CI

on:
  pull_request:
  push:
    branches:
      - main-rthrththrthrt
    paths-ignore: 
      - "**/Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    uses: timayz/.github/.github/workflows/service-testing.yml@feat/renovate
    with:
      db_name: starter
