name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: timayz/.github/.github/workflows/service-testing.yml@feat/cargo/publish
    with:
      db_name: starter

  release:
    needs: [test]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    uses: timayz/.github/.github/workflows/service-release.yml@feat/cargo/publish
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
