name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: timayz/.github/.github/workflows/service-testing.yml@feat/cargo/publish
    with:
      db_name: starter
    if: "!startsWith(github.event.commits[0].message, 'chore(release): ')"

  release:
    needs: [test]
    uses: timayz/.github/.github/workflows/service-release.yml@feat/cargo/publish
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    if: "always() && !cancelled() && !contains(needs.*.result, 'failure') && !startsWith(github.event.commits[0].message, 'chore(release): ')"
