name: Publish
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  # docker:
  #   uses: timayz/.github/.github/workflows/docker.yml@feat/cargo/publish
  #   with:
  #     image: timayz/starter
  #   secrets:
  #     DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  #     DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  cargo:
    uses: timayz/.github/.github/workflows/cargo-publish.yml@feat/cargo/publish
    with:
      publish: false
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
