name: Test
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          # package-name: release-please-action
# jobs:
# service:
#   uses: timayz/.github/.github/workflows/service-testing.yml@v2.17.0
#   with:
#     db_name: starter

