name: Test
on: pull_request

jobs:
  # service:
  #   uses: timayz/.github/.github/workflows/service-testing.yml@v2.16.0
  #   with:
  #     db_name: starter
  
  docker:
    uses: timayz/.github/.github/workflows/docker.yml@feat/setup-docker
    with:
      image: timada0/starter
    secrets:
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
