name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  service:
    uses: timayz/.github/.github/workflows/service-testing.yml@fix/service/udeps-stable
    with:
      db_name: starter
